#
#                                                                                                   
#                                     .. ....:--=++++=--:.....                                       
#                                     ...-+++++++++++++++++=:.                                       
#                                 ....:=++++++++++++++++++++*+=....                                  
#                                 ..:+++++++++++++++++++++++++++=. ..                                
#                              ....-++++++++++++++++++++++++++++++-..                                
#                              ...=+++++++++++-........-+++++++++++-...                              
#                              ..=+++++++++=...       ....=+++++++++:..                              
#                            ...-==----------::.....    ...:+++++++++.... .                          
#                           ...:----------------:...      ..:+++++++++-...                           
#                       . ...:--------------------:.      ...-++++++++++:...                         
#                       ....---------------------:..      ...-+++++++++++-..                         
#                       ...-----------::::------..        ....-=++++++++++-.                         
#                       ..:--------:........:-..             ....:+++++++++.                         
#                       ..:-------:...                          ..:++++++++-...                      
#                       ..:-------:...                           .:=+++++++=...                      
#                       ..:--------...                        ....-++++++++:...                      
#                       ...---------:.                       ....=+++++++++.. .                      
#                       ...:---------+++++++++++++++++++++++++++++++++++++..                         
#                        ...:------=+++++++++++++++++++++++++++++++++++++:.                          
#                           ..:--=+++++++++++++++++++++++++++++++++++++=....                         
#                            ...=++++++++++++++++++++++++++++++++++++-:. ..                          
#                              ....-++++++++++++++++++++++++++++++-.....                             
#                               . .   ...........................     .                              
#                                                                                                    
#       ....::::..                           .:.             ......                          ...     
#      ..:+*=--=++..                         -*.          ...=++++-..==.                    .-=.     
#      .-*-          ..............   ..... .-*. ....     .=+:.  .:..++ .....   ..  ... .....=+.     
#      .+=.  .-===+:.+****+..:**+**-..+***+*--*..+***+:   .*..      .++.-+*-++: += . *=.-++=+*+.     
#      .=+:  ....:*-=*....+*:*-. .-*:*+....*--*.*+.-**+.  :*..      .++:+:...-*.*+  .*+-*: ..=+.     
#      .:+*.. ...++:=*....+*:*-. .-*:*+...:*--*.**=....   .++.   ....++:+:...-*.++ ..*+-*:...=+.     
#        .=+****+=...=****+..:+***+:..+***+*--*..=****=.   .:+*==*+:.++.:++-++: .++-+*+.-+=-+++.     
#          ....      .....  ......  .:-...-*:..........   ..  ......... ....................  .      
#                                     -***+:.                                                        
#                                      ...  .                                                        
#
steps:
  - id: 'docker'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: [ '-' ]
    args:
      [
          'build',
          '--build-arg', 'NGINX_VERSION=${_NGINX_VERSION}',
          '--build-arg', 'NGINX_VARIANT=alpine',
          '--tag', 'us.gcr.io/${PROJECT_ID}/ncr-retail-demo:${TAG_NAME}',
          '--label', 'ncr-retail-demo-artifact=${TAG_NAME}',
          '.'
      ]

  # Helm Charts

  - id: 'publish-helm'
    name: 'us.gcr.io/odsp-management/helm:latest'
    waitFor:
      - docker
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd build/helm/charts
        export HOME="$(cat /etc/passwd | grep "^$(id -un):" | cut -d ":" -f 6)"
        helm gcs init "gs://${_HELM_STORAGE_BUCKET}"
        helm repo add gs-repository "gs://${_HELM_STORAGE_BUCKET}"

        for app_path in */; do
          app="$( echo "$(basename "$app_path")" | awk '{print tolower($0)}' )"

          echo "Publish Helm charts for ${app}"

          helm lint "$app"
          helm package "$app" --version "$TAG_NAME"
          helm gcs push "${app}-${TAG_NAME}.tgz" gs-repository --retry --force
        done

images:
  - 'us.gcr.io/${PROJECT_ID}/Voyix:${TAG_NAME}'

substitutions:
  _HELM_STORAGE_BUCKET: ''
  _NGINX_VERSION: '1.17'
